apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-kabbciwh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-kabbciwh:3137523408f8cff3c7b1f5b70a4b691ce029ac23@sha256:96c498b6d2da4c0c8432c27ea20fe529df4520c77e22fd8679af6df1f13ee703
          name: container-image
